# Generated by Django 5.0.6 on 2026-09-07 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='ชื่องาน')),
                ('description', models.TextField(blank=True, verbose_name='รายละเอียด')),
                ('date', models.DateField(verbose_name='วันที่')),
                ('start_time', models.TimeField(verbose_name='เวลาเริ่ม')),
                ('end_time', models.TimeField(verbose_name='เวลาสิ้นสุด')),
                ('priority', models.CharField(choices=[('high', 'สูง'), ('mid', 'กลาง'), ('low', 'ต่ำ')], default='mid', max_length=10, verbose_name='ความสำคัญ')),
                ('is_done', models.BooleanField(default=False, verbose_name='ทำเสร็จแล้ว')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'start_time'],
                'indexes': [models.Index(fields=['owner', 'date'], name='tasks_task_owner_i_aecdba_idx')],
            },
        ),
    ]
